# Generated by Django 2.2.3 on 2019-07-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190717_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Answer'),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
    ]
