# Generated by Django 2.2.3 on 2019-07-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190722_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ans_correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(null=True),
        ),
    ]
