# Generated by Django 2.2.3 on 2019-07-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190723_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ans_body',
            new_name='text',
        ),
    ]
