# Generated by Django 2.2.3 on 2019-07-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190723_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_answered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
    ]
