# Generated by Django 2.2.3 on 2019-07-23 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190723_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_answered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
            preserve_default=False,
        ),
    ]
